/**
 * 365-day daily verse rotation.
 *
 * Index in this array = day-of-year (1 = Jan 1, 365 = Dec 31).
 * Use `verseForToday()` to read today's verse anywhere on the site.
 * The plan is themed loosely month-by-month so the experience feels
 * intentional across the year — new beginnings in January, resurrection
 * verses around Easter, gratitude through November, incarnation in December.
 */

export interface DailyVerse {
    ref: string
    text: string
}

export const DAILY_VERSES: DailyVerse[] = [
    // ── January · New beginnings & God's call (days 1–31)
    { ref: 'Genesis 1:1',            text: 'In the beginning, God created the heavens and the earth.' },
    { ref: 'Isaiah 43:19',           text: 'Behold, I am doing a new thing; now it springs forth, do you not perceive it?' },
    { ref: '2 Corinthians 5:17',     text: 'If anyone is in Christ, he is a new creation. The old has passed away; behold, the new has come.' },
    { ref: 'Lamentations 3:22–23',   text: 'His mercies never come to an end; they are new every morning; great is your faithfulness.' },
    { ref: 'Psalm 90:12',            text: 'So teach us to number our days that we may get a heart of wisdom.' },
    { ref: 'Jeremiah 29:11',         text: 'For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.' },
    { ref: 'Proverbs 3:5–6',         text: 'Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.' },
    { ref: 'Philippians 1:6',        text: 'He who began a good work in you will bring it to completion at the day of Jesus Christ.' },
    { ref: 'Ecclesiastes 3:1',       text: 'For everything there is a season, and a time for every matter under heaven.' },
    { ref: 'Isaiah 40:31',           text: 'They who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary.' },
    { ref: 'Psalm 23:1',             text: 'The Lord is my shepherd; I shall not want.' },
    { ref: 'Romans 8:28',            text: 'And we know that for those who love God all things work together for good.' },
    { ref: 'Matthew 6:33',           text: 'Seek first the kingdom of God and his righteousness, and all these things will be added to you.' },
    { ref: 'Joshua 1:9',             text: 'Be strong and courageous. Do not be frightened, for the Lord your God is with you wherever you go.' },
    { ref: 'Psalm 139:14',           text: 'I praise you, for I am fearfully and wonderfully made.' },
    { ref: 'Isaiah 41:10',           text: 'Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you.' },
    { ref: 'Proverbs 16:9',          text: 'The heart of man plans his way, but the Lord establishes his steps.' },
    { ref: 'Psalm 37:4',             text: 'Delight yourself in the Lord, and he will give you the desires of your heart.' },
    { ref: 'Philippians 4:13',       text: 'I can do all things through him who strengthens me.' },
    { ref: 'James 1:5',              text: 'If any of you lacks wisdom, let him ask God, who gives generously to all without reproach.' },
    { ref: 'Hebrews 11:1',           text: 'Now faith is the assurance of things hoped for, the conviction of things not seen.' },
    { ref: 'Psalm 46:10',            text: 'Be still, and know that I am God.' },
    { ref: '1 Peter 5:7',            text: 'Cast all your anxieties on him, because he cares for you.' },
    { ref: 'Galatians 6:9',          text: 'Let us not grow weary of doing good, for in due season we will reap, if we do not give up.' },
    { ref: 'Romans 12:2',            text: 'Be transformed by the renewal of your mind.' },
    { ref: 'Colossians 3:23',        text: 'Whatever you do, work heartily, as for the Lord and not for men.' },
    { ref: 'Psalm 119:105',          text: 'Your word is a lamp to my feet and a light to my path.' },
    { ref: 'Isaiah 26:3',            text: 'You keep him in perfect peace whose mind is stayed on you, because he trusts in you.' },
    { ref: 'Matthew 11:28',          text: 'Come to me, all who labor and are heavy laden, and I will give you rest.' },
    { ref: 'Psalm 16:11',            text: 'You make known to me the path of life; in your presence there is fullness of joy.' },
    { ref: 'Ephesians 2:10',         text: 'We are his workmanship, created in Christ Jesus for good works.' },

    // ── February · Love (days 32–59)
    { ref: '1 Corinthians 13:4–5',   text: 'Love is patient and kind; love does not envy or boast; it is not arrogant or rude.' },
    { ref: '1 John 4:8',             text: 'Anyone who does not love does not know God, because God is love.' },
    { ref: '1 John 4:19',            text: 'We love because he first loved us.' },
    { ref: 'John 3:16',              text: 'For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.' },
    { ref: 'Romans 5:8',             text: 'God shows his love for us in that while we were still sinners, Christ died for us.' },
    { ref: 'John 13:34',             text: 'A new commandment I give to you, that you love one another: just as I have loved you.' },
    { ref: '1 Peter 4:8',            text: 'Above all, keep loving one another earnestly, since love covers a multitude of sins.' },
    { ref: 'Song of Solomon 8:7',    text: 'Many waters cannot quench love, neither can floods drown it.' },
    { ref: '1 John 3:16',            text: 'By this we know love, that he laid down his life for us.' },
    { ref: 'Proverbs 17:17',         text: 'A friend loves at all times, and a brother is born for adversity.' },
    { ref: 'Romans 13:8',            text: 'Owe no one anything, except to love each other, for the one who loves another has fulfilled the law.' },
    { ref: '1 Corinthians 13:13',    text: 'So now faith, hope, and love abide, these three; but the greatest of these is love.' },
    { ref: 'Galatians 5:22–23',      text: 'The fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.' },
    { ref: 'Ephesians 3:17–18',      text: 'May you, being rooted and grounded in love, have strength to comprehend with all the saints what is the breadth and length and height and depth.' },
    { ref: 'Colossians 3:14',        text: 'Above all these put on love, which binds everything together in perfect harmony.' },
    { ref: '1 Corinthians 16:14',    text: 'Let all that you do be done in love.' },
    { ref: 'Romans 8:38–39',         text: 'Nothing in all creation will be able to separate us from the love of God in Christ Jesus our Lord.' },
    { ref: '1 John 4:18',            text: 'There is no fear in love, but perfect love casts out fear.' },
    { ref: 'Psalm 136:1',            text: 'Give thanks to the Lord, for he is good, for his steadfast love endures forever.' },
    { ref: 'Zephaniah 3:17',         text: 'The Lord your God is in your midst, a mighty one who will save; he will rejoice over you with gladness.' },
    { ref: '1 John 4:11',            text: 'Beloved, if God so loved us, we also ought to love one another.' },
    { ref: 'John 15:13',             text: 'Greater love has no one than this, that someone lay down his life for his friends.' },
    { ref: 'Ephesians 4:2',          text: 'With all humility and gentleness, with patience, bearing with one another in love.' },
    { ref: '1 Thessalonians 3:12',   text: 'May the Lord make you increase and abound in love for one another and for all.' },
    { ref: '1 Corinthians 13:7',     text: 'Love bears all things, believes all things, hopes all things, endures all things.' },
    { ref: '1 John 4:7',             text: 'Beloved, let us love one another, for love is from God.' },
    { ref: 'Psalm 86:15',            text: 'But you, O Lord, are a God merciful and gracious, slow to anger and abounding in steadfast love and faithfulness.' },
    { ref: 'Lamentations 3:25',      text: 'The Lord is good to those who wait for him, to the soul who seeks him.' },

    // ── March · Trust & faith (days 60–90)
    { ref: 'Proverbs 3:5',           text: 'Trust in the Lord with all your heart, and do not lean on your own understanding.' },
    { ref: 'Mark 11:22',             text: 'Have faith in God.' },
    { ref: 'Hebrews 11:6',           text: 'Without faith it is impossible to please him.' },
    { ref: 'Psalm 56:3',             text: 'When I am afraid, I put my trust in you.' },
    { ref: 'Romans 10:17',           text: 'So faith comes from hearing, and hearing through the word of Christ.' },
    { ref: '2 Corinthians 5:7',      text: 'For we walk by faith, not by sight.' },
    { ref: 'Mark 9:23',              text: 'All things are possible for one who believes.' },
    { ref: 'Matthew 17:20',          text: 'If you have faith like a grain of mustard seed, you will say to this mountain, Move from here to there, and it will move.' },
    { ref: 'James 1:2–3',            text: 'Count it all joy when you meet trials of various kinds, for the testing of your faith produces steadfastness.' },
    { ref: 'Romans 4:20–21',         text: 'No unbelief made him waver concerning the promise of God, but he grew strong in his faith.' },
    { ref: 'Galatians 2:20',         text: 'It is no longer I who live, but Christ who lives in me.' },
    { ref: 'Ephesians 6:16',         text: 'In all circumstances take up the shield of faith, with which you can extinguish all the flaming darts of the evil one.' },
    { ref: '1 Peter 1:7',            text: 'The tested genuineness of your faith is more precious than gold that perishes.' },
    { ref: '1 John 5:4',             text: 'This is the victory that has overcome the world — our faith.' },
    { ref: 'Hebrews 12:2',           text: 'Looking to Jesus, the founder and perfecter of our faith.' },
    { ref: 'Psalm 91:2',             text: 'I will say to the Lord, "My refuge and my fortress, my God, in whom I trust."' },
    { ref: 'Isaiah 26:4',            text: 'Trust in the Lord forever, for the Lord God is an everlasting rock.' },
    { ref: 'Psalm 28:7',             text: 'The Lord is my strength and my shield; in him my heart trusts, and I am helped.' },
    { ref: 'Proverbs 29:25',         text: 'The fear of man lays a snare, but whoever trusts in the Lord is safe.' },
    { ref: 'Psalm 31:14',            text: 'But I trust in you, O Lord; I say, "You are my God."' },
    { ref: 'Jeremiah 17:7',          text: 'Blessed is the man who trusts in the Lord, whose trust is the Lord.' },
    { ref: 'Habakkuk 2:4',           text: 'The righteous shall live by his faith.' },
    { ref: '1 Corinthians 2:5',      text: 'Your faith might not rest in the wisdom of men but in the power of God.' },
    { ref: '2 Timothy 1:7',          text: 'God gave us a spirit not of fear but of power and love and self-control.' },
    { ref: 'Matthew 21:22',          text: 'Whatever you ask in prayer, you will receive, if you have faith.' },
    { ref: 'Psalm 13:5',             text: 'I have trusted in your steadfast love; my heart shall rejoice in your salvation.' },
    { ref: 'Psalm 34:8',             text: 'Oh, taste and see that the Lord is good! Blessed is the man who takes refuge in him!' },
    { ref: '2 Chronicles 16:9',      text: 'The eyes of the Lord run to and fro throughout the whole earth, to give strong support to those whose heart is blameless toward him.' },
    { ref: 'Romans 15:13',           text: 'May the God of hope fill you with all joy and peace in believing.' },
    { ref: 'Psalm 18:2',             text: 'The Lord is my rock and my fortress and my deliverer.' },
    { ref: 'Isaiah 12:2',            text: 'Behold, God is my salvation; I will trust, and will not be afraid.' },

    // ── April · Resurrection & hope (days 91–120)
    { ref: 'Matthew 28:6',           text: 'He is not here, for he has risen, as he said.' },
    { ref: 'John 11:25',             text: 'I am the resurrection and the life. Whoever believes in me, though he die, yet shall he live.' },
    { ref: 'Romans 6:4',             text: 'We were buried therefore with him by baptism into death, in order that we too might walk in newness of life.' },
    { ref: '1 Corinthians 15:55',    text: 'O death, where is your victory? O death, where is your sting?' },
    { ref: '1 Peter 1:3',            text: 'According to his great mercy, he has caused us to be born again to a living hope through the resurrection of Jesus Christ from the dead.' },
    { ref: 'Revelation 21:4',        text: 'He will wipe away every tear from their eyes, and death shall be no more.' },
    { ref: 'Hebrews 6:19',           text: 'We have this as a sure and steadfast anchor of the soul.' },
    { ref: 'Romans 8:24–25',         text: 'For in this hope we were saved. Now hope that is seen is not hope. We wait for it with patience.' },
    { ref: 'Psalm 42:11',            text: 'Why are you cast down, O my soul? Hope in God; for I shall again praise him.' },
    { ref: 'Romans 5:5',             text: 'Hope does not put us to shame, because God\'s love has been poured into our hearts.' },
    { ref: 'Lamentations 3:21–22',   text: 'But this I call to mind, and therefore I have hope: the steadfast love of the Lord never ceases.' },
    { ref: 'Jeremiah 31:17',         text: 'There is hope for your future, declares the Lord.' },
    { ref: 'Psalm 33:18',            text: 'Behold, the eye of the Lord is on those who fear him, on those who hope in his steadfast love.' },
    { ref: 'Titus 2:13',             text: 'Waiting for our blessed hope, the appearing of the glory of our great God and Savior Jesus Christ.' },
    { ref: 'Colossians 1:27',        text: 'Christ in you, the hope of glory.' },
    { ref: 'Hebrews 10:23',          text: 'Let us hold fast the confession of our hope without wavering, for he who promised is faithful.' },
    { ref: 'Isaiah 25:8',            text: 'He will swallow up death forever; and the Lord God will wipe away tears from all faces.' },
    { ref: 'Acts 4:12',              text: 'There is salvation in no one else, for there is no other name under heaven given among men by which we must be saved.' },
    { ref: 'John 20:29',             text: 'Blessed are those who have not seen and yet have believed.' },
    { ref: 'Romans 4:25',            text: 'He was delivered up for our trespasses and raised for our justification.' },
    { ref: '1 Corinthians 15:20',    text: 'But in fact Christ has been raised from the dead, the firstfruits of those who have fallen asleep.' },
    { ref: 'Psalm 16:9–10',          text: 'My flesh also dwells secure. For you will not abandon my soul to Sheol.' },
    { ref: 'Romans 8:11',            text: 'The Spirit of him who raised Jesus from the dead dwells in you.' },
    { ref: '2 Corinthians 4:14',     text: 'He who raised the Lord Jesus will raise us also with Jesus.' },
    { ref: 'Philippians 3:10',       text: 'That I may know him and the power of his resurrection.' },
    { ref: 'Ephesians 1:18',         text: 'That you may know what is the hope to which he has called you.' },
    { ref: 'Psalm 71:14',            text: 'I will hope continually and will praise you yet more and more.' },
    { ref: '2 Corinthians 1:10',     text: 'He delivered us from such a deadly peril, and he will deliver us. On him we have set our hope.' },
    { ref: 'Romans 15:4',            text: 'Through endurance and through the encouragement of the Scriptures we might have hope.' },
    { ref: 'Psalm 130:5',            text: 'I wait for the Lord, my soul waits, and in his word I hope.' },

    // ── May · Family & community (days 121–151)
    { ref: 'Psalm 68:6',             text: 'God settles the solitary in a home.' },
    { ref: 'Hebrews 10:24–25',       text: 'Let us consider how to stir up one another to love and good works, not neglecting to meet together.' },
    { ref: 'Ephesians 4:32',         text: 'Be kind to one another, tenderhearted, forgiving one another.' },
    { ref: 'Galatians 6:2',          text: 'Bear one another\'s burdens, and so fulfill the law of Christ.' },
    { ref: 'Romans 12:10',           text: 'Love one another with brotherly affection. Outdo one another in showing honor.' },
    { ref: 'Proverbs 27:17',         text: 'Iron sharpens iron, and one man sharpens another.' },
    { ref: 'Acts 2:42',              text: 'They devoted themselves to the apostles\' teaching and the fellowship, to the breaking of bread and the prayers.' },
    { ref: '1 Peter 4:9',            text: 'Show hospitality to one another without grumbling.' },
    { ref: 'Colossians 3:13',        text: 'Bearing with one another and, if one has a complaint against another, forgiving each other.' },
    { ref: '1 Thessalonians 5:11',   text: 'Encourage one another and build one another up.' },
    { ref: 'Ecclesiastes 4:9–10',    text: 'Two are better than one. If they fall, one will lift up his fellow.' },
    { ref: 'Psalm 133:1',            text: 'Behold, how good and pleasant it is when brothers dwell in unity!' },
    { ref: 'Proverbs 22:6',          text: 'Train up a child in the way he should go; even when he is old he will not depart from it.' },
    { ref: 'Deuteronomy 6:6–7',      text: 'These words that I command you today shall be on your heart. You shall teach them diligently to your children.' },
    { ref: 'Ephesians 5:25',         text: 'Husbands, love your wives, as Christ loved the church and gave himself up for her.' },
    { ref: 'Joshua 24:15',           text: 'As for me and my house, we will serve the Lord.' },
    { ref: 'Psalm 127:3',            text: 'Behold, children are a heritage from the Lord.' },
    { ref: 'Proverbs 31:25',         text: 'Strength and dignity are her clothing, and she laughs at the time to come.' },
    { ref: 'Mark 10:14',             text: 'Let the children come to me; do not hinder them.' },
    { ref: '1 John 3:1',             text: 'See what kind of love the Father has given to us, that we should be called children of God.' },
    { ref: 'Romans 12:5',            text: 'We, though many, are one body in Christ, and individually members one of another.' },
    { ref: '1 Corinthians 12:27',    text: 'Now you are the body of Christ and individually members of it.' },
    { ref: 'Ephesians 4:3',          text: 'Eager to maintain the unity of the Spirit in the bond of peace.' },
    { ref: 'Philippians 2:3',        text: 'Count others more significant than yourselves.' },
    { ref: 'Galatians 3:28',         text: 'There is neither Jew nor Greek, there is neither slave nor free; for you are all one in Christ Jesus.' },
    { ref: 'Romans 15:7',            text: 'Welcome one another as Christ has welcomed you.' },
    { ref: '1 Peter 3:8',            text: 'Have unity of mind, sympathy, brotherly love, a tender heart, and a humble mind.' },
    { ref: 'James 5:16',             text: 'Confess your sins to one another and pray for one another, that you may be healed.' },
    { ref: 'Proverbs 18:24',         text: 'There is a friend who sticks closer than a brother.' },
    { ref: 'Romans 12:13',           text: 'Contribute to the needs of the saints and seek to show hospitality.' },
    { ref: '1 Thessalonians 5:14',   text: 'Admonish the idle, encourage the fainthearted, help the weak, be patient with them all.' },

    // ── June · Mission & purpose (days 152–181)
    { ref: 'Matthew 28:19',          text: 'Go therefore and make disciples of all nations.' },
    { ref: 'Acts 1:8',               text: 'You will be my witnesses in Jerusalem and in all Judea and Samaria, and to the end of the earth.' },
    { ref: 'Mark 16:15',             text: 'Go into all the world and proclaim the gospel to the whole creation.' },
    { ref: 'Matthew 5:14',           text: 'You are the light of the world. A city set on a hill cannot be hidden.' },
    { ref: 'Matthew 5:16',           text: 'Let your light shine before others, so that they may see your good works and give glory to your Father.' },
    { ref: 'Romans 10:14',           text: 'How are they to believe in him of whom they have never heard?' },
    { ref: 'Isaiah 6:8',             text: 'Here I am! Send me.' },
    { ref: 'Ephesians 4:11–12',      text: 'He gave the apostles, the prophets, the evangelists, the shepherds and teachers, to equip the saints.' },
    { ref: '1 Peter 2:9',            text: 'You are a chosen race, a royal priesthood, a holy nation, a people for his own possession.' },
    { ref: 'Acts 20:24',             text: 'I do not account my life of any value nor as precious to myself, if only I may finish my course.' },
    { ref: 'Philippians 1:21',       text: 'For to me to live is Christ, and to die is gain.' },
    { ref: '2 Timothy 4:7',          text: 'I have fought the good fight, I have finished the race, I have kept the faith.' },
    { ref: 'Hebrews 12:1',           text: 'Let us also lay aside every weight, and let us run with endurance the race that is set before us.' },
    { ref: 'Colossians 4:5–6',       text: 'Walk in wisdom toward outsiders, making the best use of the time.' },
    { ref: '1 Corinthians 9:22',     text: 'I have become all things to all people, that by all means I might save some.' },
    { ref: 'Romans 1:16',            text: 'I am not ashamed of the gospel, for it is the power of God for salvation.' },
    { ref: 'Matthew 9:37–38',        text: 'The harvest is plentiful, but the laborers are few; therefore pray earnestly to the Lord of the harvest.' },
    { ref: 'John 4:35',              text: 'Lift up your eyes, and see that the fields are white for harvest.' },
    { ref: '2 Corinthians 5:20',     text: 'We are ambassadors for Christ, God making his appeal through us.' },
    { ref: 'Ephesians 6:19',         text: 'Pray that words may be given to me in opening my mouth boldly to proclaim the mystery of the gospel.' },
    { ref: '1 Peter 3:15',           text: 'Always being prepared to make a defense to anyone who asks you for a reason for the hope that is in you.' },
    { ref: 'Proverbs 11:30',         text: 'The fruit of the righteous is a tree of life, and whoever captures souls is wise.' },
    { ref: 'Romans 12:1',            text: 'Present your bodies as a living sacrifice, holy and acceptable to God.' },
    { ref: '1 Corinthians 3:9',      text: 'For we are God\'s fellow workers.' },
    { ref: 'Luke 19:10',             text: 'For the Son of Man came to seek and to save the lost.' },
    { ref: 'Psalm 67:2',             text: 'That your way may be known on earth, your saving power among all nations.' },
    { ref: 'Isaiah 52:7',            text: 'How beautiful upon the mountains are the feet of him who brings good news.' },
    { ref: 'Acts 4:20',              text: 'We cannot but speak of what we have seen and heard.' },
    { ref: 'James 5:20',             text: 'Whoever brings back a sinner from his wandering will save his soul from death.' },
    { ref: '1 Timothy 2:4',          text: 'God desires all people to be saved and to come to the knowledge of the truth.' },

    // ── July · Freedom & identity in Christ (days 182–212)
    { ref: 'Galatians 5:1',          text: 'For freedom Christ has set us free; stand firm therefore.' },
    { ref: 'John 8:36',              text: 'If the Son sets you free, you will be free indeed.' },
    { ref: 'Romans 8:1',             text: 'There is therefore now no condemnation for those who are in Christ Jesus.' },
    { ref: 'Romans 8:15',            text: 'You have received the Spirit of adoption as sons, by whom we cry, "Abba! Father!"' },
    { ref: '2 Corinthians 3:17',     text: 'Where the Spirit of the Lord is, there is freedom.' },
    { ref: 'John 1:12',              text: 'But to all who did receive him, he gave the right to become children of God.' },
    { ref: 'Ephesians 1:5',          text: 'He predestined us for adoption to himself as sons through Jesus Christ.' },
    { ref: 'Galatians 3:26',         text: 'In Christ Jesus you are all sons of God, through faith.' },
    { ref: 'Galatians 4:7',          text: 'You are no longer a slave, but a son.' },
    { ref: 'Romans 6:6',             text: 'We know that our old self was crucified with him so that we would no longer be enslaved to sin.' },
    { ref: 'Romans 6:14',            text: 'Sin will have no dominion over you, since you are not under law but under grace.' },
    { ref: 'Colossians 2:13–14',     text: 'God made us alive together with him, having forgiven us all our trespasses.' },
    { ref: '1 Peter 2:16',           text: 'Live as people who are free, not using your freedom as a cover-up for evil, but living as servants of God.' },
    { ref: 'Hebrews 4:16',           text: 'Let us then with confidence draw near to the throne of grace.' },
    { ref: 'Ephesians 2:8–9',        text: 'For by grace you have been saved through faith. And this is not your own doing; it is the gift of God.' },
    { ref: 'Romans 5:1',             text: 'Therefore, since we have been justified by faith, we have peace with God.' },
    { ref: '2 Corinthians 5:21',     text: 'For our sake he made him to be sin who knew no sin, so that in him we might become the righteousness of God.' },
    { ref: 'Isaiah 61:1',            text: 'The Spirit of the Lord God is upon me, because the Lord has anointed me to bring good news to the poor.' },
    { ref: 'Luke 4:18',              text: 'He has sent me to proclaim liberty to the captives and recovering of sight to the blind.' },
    { ref: 'Romans 8:21',            text: 'The creation itself will be set free from its bondage to corruption.' },
    { ref: 'Romans 8:37',            text: 'In all these things we are more than conquerors through him who loved us.' },
    { ref: '1 John 5:14',            text: 'This is the confidence that we have toward him, that if we ask anything according to his will he hears us.' },
    { ref: 'Hebrews 10:19',          text: 'We have confidence to enter the holy places by the blood of Jesus.' },
    { ref: 'Ephesians 3:12',         text: 'In him we have boldness and access with confidence through our faith in him.' },
    { ref: 'Psalm 27:1',             text: 'The Lord is my light and my salvation; whom shall I fear?' },
    { ref: 'Romans 8:39',            text: 'Nothing in all creation will be able to separate us from the love of God in Christ Jesus.' },
    { ref: 'Galatians 2:16',         text: 'A person is not justified by works of the law but through faith in Jesus Christ.' },
    { ref: 'Romans 3:24',            text: 'Justified by his grace as a gift, through the redemption that is in Christ Jesus.' },
    { ref: 'Ephesians 1:7',          text: 'In him we have redemption through his blood, the forgiveness of our trespasses.' },
    { ref: '1 Corinthians 6:11',     text: 'But you were washed, you were sanctified, you were justified in the name of the Lord Jesus Christ.' },
    { ref: 'Isaiah 43:1',            text: 'Fear not, for I have redeemed you; I have called you by name, you are mine.' },

    // ── August · Wisdom (days 213–243)
    { ref: 'Proverbs 9:10',          text: 'The fear of the Lord is the beginning of wisdom, and the knowledge of the Holy One is insight.' },
    { ref: 'Proverbs 1:7',           text: 'The fear of the Lord is the beginning of knowledge.' },
    { ref: 'James 3:17',             text: 'The wisdom from above is first pure, then peaceable, gentle, open to reason.' },
    { ref: 'Proverbs 2:6',           text: 'For the Lord gives wisdom; from his mouth come knowledge and understanding.' },
    { ref: 'Proverbs 4:7',           text: 'The beginning of wisdom is this: Get wisdom, and whatever you get, get insight.' },
    { ref: '1 Corinthians 1:25',     text: 'The foolishness of God is wiser than men, and the weakness of God is stronger than men.' },
    { ref: 'Ecclesiastes 7:12',      text: 'The advantage of knowledge is that wisdom preserves the life of him who has it.' },
    { ref: 'Psalm 111:10',           text: 'The fear of the Lord is the beginning of wisdom; all those who practice it have a good understanding.' },
    { ref: 'Proverbs 11:2',          text: 'When pride comes, then comes disgrace, but with the humble is wisdom.' },
    { ref: 'Job 28:28',              text: 'Behold, the fear of the Lord, that is wisdom, and to turn away from evil is understanding.' },
    { ref: 'Proverbs 19:20',         text: 'Listen to advice and accept instruction, that you may gain wisdom in the future.' },
    { ref: 'Colossians 2:3',         text: 'In whom are hidden all the treasures of wisdom and knowledge.' },
    { ref: 'Proverbs 13:20',         text: 'Whoever walks with the wise becomes wise.' },
    { ref: 'Proverbs 16:16',         text: 'How much better to get wisdom than gold!' },
    { ref: 'James 1:6',              text: 'Let him ask in faith, with no doubting, for the one who doubts is like a wave of the sea.' },
    { ref: 'Proverbs 8:11',          text: 'For wisdom is better than jewels, and all that you may desire cannot compare with her.' },
    { ref: 'Ephesians 5:15–16',      text: 'Look carefully then how you walk, not as unwise but as wise, making the best use of the time.' },
    { ref: 'Proverbs 14:8',          text: 'The wisdom of the prudent is to discern his way.' },
    { ref: 'Proverbs 12:15',         text: 'The way of a fool is right in his own eyes, but a wise man listens to advice.' },
    { ref: 'Ecclesiastes 9:18',      text: 'Wisdom is better than weapons of war.' },
    { ref: '1 Corinthians 3:18',     text: 'Let no one deceive himself. If anyone among you thinks that he is wise in this age, let him become a fool that he may become wise.' },
    { ref: 'Proverbs 3:13',          text: 'Blessed is the one who finds wisdom, and the one who gets understanding.' },
    { ref: '1 Kings 3:9',            text: 'Give your servant therefore an understanding mind to govern your people.' },
    { ref: 'Daniel 2:21',            text: 'He gives wisdom to the wise and knowledge to those who have understanding.' },
    { ref: 'Romans 11:33',           text: 'Oh, the depth of the riches and wisdom and knowledge of God!' },
    { ref: 'Psalm 51:6',             text: 'You teach me wisdom in the secret heart.' },
    { ref: 'Proverbs 24:3–4',        text: 'By wisdom a house is built, and by understanding it is established.' },
    { ref: 'Ecclesiastes 12:13',     text: 'Fear God and keep his commandments, for this is the whole duty of man.' },
    { ref: 'Proverbs 15:33',         text: 'The fear of the Lord is instruction in wisdom, and humility comes before honor.' },
    { ref: 'James 3:13',             text: 'Who is wise and understanding among you? By his good conduct let him show his works in the meekness of wisdom.' },
    { ref: 'Psalm 90:12',            text: 'So teach us to number our days that we may get a heart of wisdom.' },

    // ── September · Renewed mind & transformation (days 244–273)
    { ref: 'Romans 12:2',            text: 'Do not be conformed to this world, but be transformed by the renewal of your mind.' },
    { ref: 'Ephesians 4:23',         text: 'Be renewed in the spirit of your minds.' },
    { ref: 'Colossians 3:2',         text: 'Set your minds on things that are above, not on things that are on earth.' },
    { ref: '2 Corinthians 4:16',     text: 'Though our outer self is wasting away, our inner self is being renewed day by day.' },
    { ref: 'Philippians 4:8',        text: 'Whatever is true, whatever is honorable, whatever is just — think about these things.' },
    { ref: 'Psalm 51:10',            text: 'Create in me a clean heart, O God, and renew a right spirit within me.' },
    { ref: 'Romans 8:6',             text: 'To set the mind on the Spirit is life and peace.' },
    { ref: 'Isaiah 40:31',           text: 'They who wait for the Lord shall renew their strength.' },
    { ref: 'Titus 3:5',              text: 'He saved us by the washing of regeneration and renewal of the Holy Spirit.' },
    { ref: '1 Corinthians 2:16',     text: 'But we have the mind of Christ.' },
    { ref: 'Hebrews 12:11',          text: 'Discipline yields the peaceful fruit of righteousness to those who have been trained by it.' },
    { ref: 'Philippians 2:5',        text: 'Have this mind among yourselves, which is yours in Christ Jesus.' },
    { ref: 'Romans 6:11',            text: 'Consider yourselves dead to sin and alive to God in Christ Jesus.' },
    { ref: 'Ezekiel 36:26',          text: 'I will give you a new heart, and a new spirit I will put within you.' },
    { ref: 'Psalm 19:14',            text: 'Let the words of my mouth and the meditation of my heart be acceptable in your sight, O Lord.' },
    { ref: 'James 1:21',             text: 'Receive with meekness the implanted word, which is able to save your souls.' },
    { ref: 'Galatians 5:16',         text: 'Walk by the Spirit, and you will not gratify the desires of the flesh.' },
    { ref: 'Colossians 3:10',        text: 'You have put on the new self, which is being renewed in knowledge after the image of its creator.' },
    { ref: 'Romans 6:13',            text: 'Present yourselves to God as those who have been brought from death to life.' },
    { ref: 'Hebrews 10:22',          text: 'Let us draw near with a true heart in full assurance of faith.' },
    { ref: 'Psalm 23:3',             text: 'He restores my soul. He leads me in paths of righteousness for his name\'s sake.' },
    { ref: 'Isaiah 26:9',            text: 'My soul yearns for you in the night; my spirit within me earnestly seeks you.' },
    { ref: '2 Peter 3:18',           text: 'Grow in the grace and knowledge of our Lord and Savior Jesus Christ.' },
    { ref: 'Ephesians 4:24',         text: 'Put on the new self, created after the likeness of God in true righteousness and holiness.' },
    { ref: 'Romans 13:14',           text: 'Put on the Lord Jesus Christ, and make no provision for the flesh.' },
    { ref: 'John 15:5',              text: 'I am the vine; you are the branches. Whoever abides in me and I in him, he it is that bears much fruit.' },
    { ref: 'Galatians 2:20',         text: 'I have been crucified with Christ. It is no longer I who live, but Christ who lives in me.' },
    { ref: 'Hebrews 13:8',           text: 'Jesus Christ is the same yesterday and today and forever.' },
    { ref: 'Philippians 3:13–14',    text: 'Forgetting what lies behind and straining forward to what lies ahead, I press on toward the goal.' },
    { ref: 'Psalm 73:26',            text: 'God is the strength of my heart and my portion forever.' },

    // ── October · Gratitude & harvest (days 274–304)
    { ref: '1 Thessalonians 5:18',   text: 'Give thanks in all circumstances; for this is the will of God in Christ Jesus for you.' },
    { ref: 'Psalm 100:4',            text: 'Enter his gates with thanksgiving, and his courts with praise!' },
    { ref: 'Colossians 3:17',        text: 'Whatever you do, in word or deed, do everything in the name of the Lord Jesus, giving thanks to God.' },
    { ref: 'Psalm 107:1',            text: 'Oh give thanks to the Lord, for he is good, for his steadfast love endures forever!' },
    { ref: 'Philippians 4:6–7',      text: 'With thanksgiving let your requests be made known to God.' },
    { ref: 'Ephesians 5:20',         text: 'Giving thanks always and for everything to God the Father.' },
    { ref: '2 Corinthians 9:15',     text: 'Thanks be to God for his inexpressible gift!' },
    { ref: 'Psalm 95:2',             text: 'Let us come into his presence with thanksgiving; let us make a joyful noise to him with songs of praise!' },
    { ref: '1 Chronicles 16:34',     text: 'Oh give thanks to the Lord, for he is good; for his steadfast love endures forever!' },
    { ref: 'Hebrews 13:15',          text: 'Through him then let us continually offer up a sacrifice of praise to God.' },
    { ref: 'Psalm 9:1',              text: 'I will give thanks to the Lord with my whole heart; I will recount all of your wonderful deeds.' },
    { ref: 'Galatians 6:7',          text: 'Do not be deceived: God is not mocked, for whatever one sows, that will he also reap.' },
    { ref: '2 Corinthians 9:6',      text: 'Whoever sows sparingly will also reap sparingly, and whoever sows bountifully will also reap bountifully.' },
    { ref: 'Hosea 10:12',            text: 'Sow for yourselves righteousness; reap steadfast love.' },
    { ref: 'Psalm 126:5–6',          text: 'Those who sow in tears shall reap with shouts of joy!' },
    { ref: 'James 3:18',             text: 'A harvest of righteousness is sown in peace by those who make peace.' },
    { ref: 'Matthew 13:23',          text: 'As for what was sown on good soil, this is the one who hears the word and understands it.' },
    { ref: '2 Corinthians 9:11',     text: 'You will be enriched in every way to be generous in every way.' },
    { ref: 'Proverbs 11:25',         text: 'Whoever brings blessing will be enriched, and one who waters will himself be watered.' },
    { ref: 'Luke 6:38',              text: 'Give, and it will be given to you. Good measure, pressed down, shaken together, running over.' },
    { ref: 'Malachi 3:10',           text: 'Bring the full tithe into the storehouse, that there may be food in my house.' },
    { ref: 'Proverbs 3:9–10',        text: 'Honor the Lord with your wealth and with the firstfruits of all your produce.' },
    { ref: 'Acts 20:35',             text: 'It is more blessed to give than to receive.' },
    { ref: '2 Corinthians 8:9',      text: 'Though he was rich, yet for your sake he became poor, so that you by his poverty might become rich.' },
    { ref: 'Matthew 6:21',           text: 'For where your treasure is, there your heart will be also.' },
    { ref: '1 Timothy 6:18',         text: 'Be rich in good works, to be generous and ready to share.' },
    { ref: 'Psalm 116:12',           text: 'What shall I render to the Lord for all his benefits to me?' },
    { ref: 'Lamentations 3:24',      text: 'The Lord is my portion, therefore I will hope in him.' },
    { ref: 'Psalm 34:1',             text: 'I will bless the Lord at all times; his praise shall continually be in my mouth.' },
    { ref: 'Psalm 103:2',            text: 'Bless the Lord, O my soul, and forget not all his benefits.' },
    { ref: '1 Corinthians 15:57',    text: 'Thanks be to God, who gives us the victory through our Lord Jesus Christ.' },

    // ── November · Worship & praise (days 305–334)
    { ref: 'Psalm 95:6',             text: 'Oh come, let us worship and bow down; let us kneel before the Lord, our Maker!' },
    { ref: 'John 4:24',              text: 'God is spirit, and those who worship him must worship in spirit and truth.' },
    { ref: 'Psalm 150:6',            text: 'Let everything that has breath praise the Lord!' },
    { ref: 'Psalm 96:9',             text: 'Worship the Lord in the splendor of holiness; tremble before him, all the earth!' },
    { ref: 'Psalm 29:2',             text: 'Ascribe to the Lord the glory due his name; worship the Lord in the splendor of holiness.' },
    { ref: 'Romans 12:1',            text: 'Present your bodies as a living sacrifice, holy and acceptable to God, which is your spiritual worship.' },
    { ref: 'Psalm 86:9',             text: 'All the nations you have made shall come and worship before you, O Lord.' },
    { ref: 'Hebrews 12:28',          text: 'Let us offer to God acceptable worship, with reverence and awe.' },
    { ref: 'Revelation 4:11',        text: 'Worthy are you, our Lord and God, to receive glory and honor and power.' },
    { ref: 'Psalm 145:3',            text: 'Great is the Lord, and greatly to be praised, and his greatness is unsearchable.' },
    { ref: 'Psalm 22:22',            text: 'I will tell of your name to my brothers; in the midst of the congregation I will praise you.' },
    { ref: 'Psalm 34:3',             text: 'Oh, magnify the Lord with me, and let us exalt his name together!' },
    { ref: 'Psalm 47:6',             text: 'Sing praises to God, sing praises! Sing praises to our King, sing praises!' },
    { ref: 'Psalm 63:4',             text: 'So I will bless you as long as I live; in your name I will lift up my hands.' },
    { ref: 'Ephesians 5:19',         text: 'Addressing one another in psalms and hymns and spiritual songs, singing and making melody to the Lord.' },
    { ref: 'Colossians 3:16',        text: 'Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom, singing psalms and hymns.' },
    { ref: 'Psalm 71:8',             text: 'My mouth is filled with your praise, and with your glory all the day.' },
    { ref: 'Psalm 51:15',            text: 'O Lord, open my lips, and my mouth will declare your praise.' },
    { ref: 'Psalm 27:4',             text: 'One thing have I asked of the Lord, that will I seek after: that I may dwell in the house of the Lord all the days of my life.' },
    { ref: 'Psalm 84:1–2',           text: 'How lovely is your dwelling place, O Lord of hosts! My soul longs, yes, faints for the courts of the Lord.' },
    { ref: 'Psalm 122:1',            text: 'I was glad when they said to me, "Let us go to the house of the Lord!"' },
    { ref: 'John 12:32',             text: 'And I, when I am lifted up from the earth, will draw all people to myself.' },
    { ref: 'Philippians 2:9–10',     text: 'God has highly exalted him and bestowed on him the name that is above every name.' },
    { ref: 'Revelation 5:12',        text: 'Worthy is the Lamb who was slain, to receive power and wealth and wisdom and might and honor and glory and blessing!' },
    { ref: 'Psalm 8:1',              text: 'O Lord, our Lord, how majestic is your name in all the earth!' },
    { ref: 'Psalm 19:1',             text: 'The heavens declare the glory of God, and the sky above proclaims his handiwork.' },
    { ref: 'Habakkuk 3:18',          text: 'Yet I will rejoice in the Lord; I will take joy in the God of my salvation.' },
    { ref: 'Psalm 28:7',             text: 'My heart exults, and with my song I give thanks to him.' },
    { ref: 'Psalm 89:1',             text: 'I will sing of the steadfast love of the Lord, forever; with my mouth I will make known your faithfulness.' },
    { ref: 'Psalm 105:1',            text: 'Oh give thanks to the Lord; call upon his name; make known his deeds among the peoples!' },

    // ── December · Incarnation & peace (days 335–365)
    { ref: 'Isaiah 9:6',             text: 'For to us a child is born, to us a son is given; and the government shall be upon his shoulder.' },
    { ref: 'Luke 2:11',              text: 'For unto you is born this day in the city of David a Savior, who is Christ the Lord.' },
    { ref: 'Matthew 1:23',           text: 'Behold, the virgin shall conceive and bear a son, and they shall call his name Immanuel — God with us.' },
    { ref: 'John 1:14',              text: 'And the Word became flesh and dwelt among us, and we have seen his glory.' },
    { ref: 'Luke 2:14',              text: 'Glory to God in the highest, and on earth peace among those with whom he is pleased!' },
    { ref: 'Micah 5:2',              text: 'But you, O Bethlehem Ephrathah, from you shall come forth for me one who is to be ruler in Israel.' },
    { ref: 'Galatians 4:4',          text: 'When the fullness of time had come, God sent forth his Son, born of woman.' },
    { ref: 'John 3:17',              text: 'For God did not send his Son into the world to condemn the world, but in order that the world might be saved through him.' },
    { ref: 'Philippians 2:6–7',      text: 'Though he was in the form of God, he emptied himself, by taking the form of a servant.' },
    { ref: 'Hebrews 1:3',            text: 'He is the radiance of the glory of God and the exact imprint of his nature.' },
    { ref: '1 John 4:14',            text: 'The Father has sent his Son to be the Savior of the world.' },
    { ref: 'John 14:27',             text: 'Peace I leave with you; my peace I give to you. Not as the world gives do I give to you.' },
    { ref: 'Romans 5:1',             text: 'Therefore, since we have been justified by faith, we have peace with God through our Lord Jesus Christ.' },
    { ref: 'Philippians 4:7',        text: 'The peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.' },
    { ref: 'Colossians 3:15',        text: 'Let the peace of Christ rule in your hearts, to which indeed you were called in one body.' },
    { ref: 'Isaiah 26:3',            text: 'You keep him in perfect peace whose mind is stayed on you, because he trusts in you.' },
    { ref: 'John 16:33',             text: 'In the world you will have tribulation. But take heart; I have overcome the world.' },
    { ref: 'Numbers 6:24–26',        text: 'The Lord bless you and keep you; the Lord make his face to shine upon you and be gracious to you.' },
    { ref: 'Psalm 29:11',            text: 'May the Lord give strength to his people! May the Lord bless his people with peace!' },
    { ref: 'Romans 15:33',           text: 'May the God of peace be with you all. Amen.' },
    { ref: '2 Thessalonians 3:16',   text: 'Now may the Lord of peace himself give you peace at all times in every way.' },
    { ref: 'Matthew 5:9',            text: 'Blessed are the peacemakers, for they shall be called sons of God.' },
    { ref: 'Ephesians 2:14',         text: 'For he himself is our peace, who has made us both one and has broken down in his flesh the dividing wall of hostility.' },
    { ref: 'Romans 12:18',           text: 'If possible, so far as it depends on you, live peaceably with all.' },
    { ref: '1 Peter 3:11',           text: 'Let him turn away from evil and do good; let him seek peace and pursue it.' },
    { ref: 'Isaiah 53:5',            text: 'Upon him was the chastisement that brought us peace, and with his wounds we are healed.' },
    { ref: 'Luke 1:78–79',           text: 'Because of the tender mercy of our God, whereby the sunrise shall visit us from on high.' },
    { ref: 'Colossians 2:6–7',       text: 'Therefore, as you have received Christ Jesus the Lord, so walk in him, rooted and built up in him and established in the faith.' },
    { ref: 'Romans 16:20',           text: 'The God of peace will soon crush Satan under your feet. The grace of our Lord Jesus Christ be with you.' },
    { ref: 'Revelation 22:20',       text: 'Surely I am coming soon. Amen. Come, Lord Jesus!' },
    { ref: 'Jude 1:24–25',           text: 'Now to him who is able to keep you from stumbling and to present you blameless before the presence of his glory.' },
]

/**
 * Returns the 1-indexed day-of-year (1 = Jan 1, 365/366 = Dec 31)
 * for the local-time start of `d` (default: now).
 * Leap days clamp to 365 so Feb 29 keeps showing the Feb 28 verse.
 */
export function dayOfYear(d: Date = new Date()): number {
    const start = new Date(d.getFullYear(), 0, 0)
    const diff = d.getTime() - start.getTime()
    const day = Math.floor(diff / 86_400_000)
    return Math.min(365, Math.max(1, day))
}

/** Returns today's verse (1-indexed by day-of-year, modulo array length). */
export function verseForToday(d: Date = new Date()): DailyVerse {
    const idx = (dayOfYear(d) - 1) % DAILY_VERSES.length
    return DAILY_VERSES[idx]
}
